name: LMFDB
description: |
    Import from LMFDB.org/Knowledge
icon: img/lmfdb-logo.svg

latex_macros: |
    C: '{\\mathbb{C}}',
    R: '{\\mathbb{R}}',
    Q: '{\\mathbb{Q}}',
    Z: '{\\mathbb{Z}}',
    F: '{\\mathbb{F}}',
    H: '{\\mathbb{H}}',
    HH: '{\\mathcal{H}}',
    integers: '{\\mathcal{O}}',
    SL: '{\\textrm{SL}}',
    GL: '{\\textrm{GL}}',
    PSL: '{\\textrm{PSL}}',
    PGL: '{\\textrm{PGL}}',
    Sp: '{\\textrm{Sp}}',
    GSp: '{\\textrm{GSp}}',
    Gal: '{\\mathop{\\rm Gal}}',
    Aut: '{\\mathop{\\rm Aut}}',
    Sym: '{\\mathop{\\rm Sym}}',
    End: '{\\mathop{\\rm Reg}}',
    Reg: '{\\mathop{\\rm Res}}',
    Ord: '{\\mathop{\\rm Ord}}',
    sgn: '{\\mathop{\\rm sgn}}',
    trace: '{\\mathop{\\rm trace}}',
    Res: '{\\mathop{\\rm Res}}',
    ideal: ['{\\mathfrak{ #1 }}',1],
    classgroup: ['{Cl(#1)}',1],
    modstar: ['{\\left( #1/#2 \\right)^\\times}',2]
